# Generated by Django 6.0 on 2025-12-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_old_name_field'),
        ('orders', '0005_order_payment_confirmed_at_and_more'),
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('none', 'No Commission'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('commission_fixed_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed commission amount per order', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Settings',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to farmer', max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission deducted', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Method used to send payment (Orange Money, MTN Money, etc.)', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.farmerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payments', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order_item',)},
            },
        ),
    ]
