# Generated by Django 6.0 on 2025-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_confirmed',
            field=models.BooleanField(default=False, help_text='Whether customer has confirmed delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('not_delivered', 'Not Delivered')], default='pending', max_length=20),
        ),
    ]
