# Generated by Django 6.0 on 2025-12-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coveragearea_remove_customerprofile_address_and_more'),
        ('marketplace', '0002_make_category_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_coverage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.coveragearea'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.street'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='Legacy field - use location_coverage_area and location_street instead', max_length=255),
        ),
    ]
