# Generated by Django 6.0 on 2025-12-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Coverage Areas',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliveryagency',
            name='coverage_area',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_details',
            field=models.TextField(blank=True, help_text='Additional address details (house number, building, etc.)'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='address_details',
            field=models.TextField(blank=True, help_text='Additional address details (farm location, etc.)'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='coverage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.coveragearea'),
        ),
        migrations.AddField(
            model_name='deliveryagency',
            name='coverage_areas',
            field=models.ManyToManyField(help_text='Areas this agency covers', related_name='agencies', to='accounts.coveragearea'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='coverage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='accounts.coveragearea'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='accounts.coveragearea')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'coverage_area')},
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.street'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='accounts.street'),
        ),
    ]
