# Generated by Django 6.0 on 2025-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coveragearea_remove_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagency',
            name='address',
            field=models.TextField(blank=True, help_text='Agency address', null=True),
        ),
        migrations.AddField(
            model_name='deliveryagency',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagency',
            name='name',
            field=models.CharField(help_text='Agency name', max_length=120),
        ),
    ]
