# Generated by Django 6.0 on 2025-12-12 11:59

from django.db import migrations, models
import django.db.models.deletion


def copy_data_forward(apps, schema_editor):
    """Copy data from old fields to new fields."""
    DeliveryAgency = apps.get_model('accounts', 'DeliveryAgency')
    for agency in DeliveryAgency.objects.all():
        # Copy name to agency_name
        if not agency.agency_name:
            agency.agency_name = agency.name
        # Copy phone to phone_number
        if not agency.phone_number:
            agency.phone_number = agency.phone
        # Copy user.email to email
        if not agency.email and agency.user:
            agency.email = agency.user.email
        # Copy first coverage area if exists
        if not agency.coverage_area and agency.coverage_areas.exists():
            agency.coverage_area = agency.coverage_areas.first()
        agency.save()


def copy_data_backward(apps, schema_editor):
    """Copy data back from new fields to old fields."""
    DeliveryAgency = apps.get_model('accounts', 'DeliveryAgency')
    for agency in DeliveryAgency.objects.all():
        # Copy agency_name to name
        if agency.agency_name:
            agency.name = agency.agency_name
        # Copy phone_number to phone
        if agency.phone_number:
            agency.phone = agency.phone_number
        agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryagency_address_deliveryagency_phone_and_more'),
    ]

    operations = [
        # Step 1: Add new fields (nullable first)
        migrations.AddField(
            model_name='deliveryagency',
            name='email',
            field=models.EmailField(help_text='Email for login', max_length=254, null=True, unique=True, blank=True),
        ),
        migrations.AddField(
            model_name='deliveryagency',
            name='agency_name',
            field=models.CharField(help_text='Agency name', max_length=120, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='deliveryagency',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagency',
            name='coverage_area',
            field=models.ForeignKey(blank=True, help_text='Primary coverage area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_new', to='accounts.coveragearea'),
        ),
        
        # Step 2: Copy data
        migrations.RunPython(copy_data_forward, copy_data_backward),
        
        # Step 3: Remove old ManyToMany field
        migrations.RemoveField(
            model_name='deliveryagency',
            name='coverage_areas',
        ),
        
        # Step 4: Rename user to account
        migrations.RenameField(
            model_name='deliveryagency',
            old_name='user',
            new_name='account',
        ),
        
        # Step 5: Remove old fields (name and phone will be removed, but we keep name as alias)
        migrations.RemoveField(
            model_name='deliveryagency',
            name='phone',
        ),
        
        # Step 6: Make new fields required (except phone_number and address which can be null)
        migrations.AlterField(
            model_name='deliveryagency',
            name='email',
            field=models.EmailField(help_text='Email for login', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryagency',
            name='agency_name',
            field=models.CharField(help_text='Agency name', max_length=120),
        ),
        
        # Step 7: Fix related_name for coverage_area
        migrations.AlterField(
            model_name='deliveryagency',
            name='coverage_area',
            field=models.ForeignKey(blank=True, help_text='Primary coverage area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='accounts.coveragearea'),
        ),
    ]
