# Generated by Django 6.0 on 2025-12-12 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_delivery_agency_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryagency',
            options={'verbose_name': 'Delivery Agency', 'verbose_name_plural': 'Delivery Agencies'},
        ),
        migrations.RemoveField(
            model_name='deliveryagency',
            name='name',
        ),
        migrations.AlterField(
            model_name='deliveryagency',
            name='account',
            field=models.OneToOneField(help_text='User account', on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
