# Generated by Django 6.0 on 2025-12-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_old_name_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='coverage_area',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='street',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address_details',
            field=models.TextField(blank=True, help_text='General address information (optional)'),
        ),
    ]
