# Generated by Django 6.0 on 2025-12-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customerprofile_coverage_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='coverage_area',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='street',
            field=models.ForeignKey(blank=True, help_text='Street/neighborhood where the customer is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.street'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address_details',
            field=models.TextField(blank=True, help_text='Additional address details (house number, building, etc.)'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='street',
            field=models.ForeignKey(blank=True, help_text='Street/neighborhood where the farm is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='accounts.street'),
        ),
    ]
