# Generated by Django 6.0 on 2025-12-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coveragearea_remove_customerprofile_address_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_details',
            field=models.TextField(blank=True, help_text='Additional delivery address details'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_coverage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.coveragearea'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.street'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
    ]
