# Generated by Django 6.0 on 2025-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_received',
            field=models.BooleanField(default=False, help_text='Whether the farmer has received payment for this item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
